import React from 'react';

import BackArrow from '@/components/BackArrow/BackArrow';
import styles from '@/app/privacy_policy/page.module.css';

const PrivacyPolicy = () => {
    return (
        <div className={styles.container}>
            <div className={styles.backArrow}>
                <BackArrow />
            </div>
            <div>
                <h1 className={styles.title}>Privacy Policy</h1>
                <p className={styles.paragraph}>Last updated: September 11, 2024</p>
                <p className={styles.paragraph}>
                    This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service...
                </p>
                <h2 className={styles.subtitle}>Interpretation and Definitions</h2>
                <p className={styles.paragraph}>
                    The words of which the initial letter is capitalized have meanings defined under the following conditions...
                </p>
                <h3>Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className={styles.list}>
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> refers to The Nook Journal.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to Spain.</li>
                    <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> refers to third-party companies or individuals employed by the Company to facilitate the Service or to provide the Service on behalf of the Company.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to The Nook Journal, accessible from <a href="https://thenookjournal.com" target="_blank" rel="noopener">https://thenookjournal.com</a></li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company on behalf of which such individual is accessing or using the Service.</li>
                </ul>

                {/* Add the rest of the content here */}

                <h2 className={styles.subtitle}>Contact Us</h2>
                <p className={styles.paragraph}>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className={styles.list}>
                    <li>By email: thenookjournal@gmail.com</li>
                </ul>
            </div>
        </div>
        
    );
};

export default PrivacyPolicy;
